### ISSUE TITLE
lesson 08  publish  

### ISSUE THREAD

**Issue by leonaaaardo** [npm/how-to-npm#105]
when I type "how-to-npm verify",it print "Looking sharp!
A package without a readme and some metadata is like a
bunch of JavaScript without instructions or git repo links."
why? I've add the "readme" into the "package.json" file 
  "readme": "README.md",

**Comment by watilde** [comment]
Hello! Did you mean `07-package-niceties`? The printed message actually means **Sucess**, so please don't worry about it. Also, you don't need to put `readme` filed into your `package.json`.
+ https://github.com/workshopper/how-to-npm/blob/master/i18n/en.json#L47

Maybe we can tweak the message to clarify.

**Comment by cinyearchan** [comment]
thank you

**Comment by watilde** [comment]
Closing as resolved, but if you haven't resolved it yet, please do not hesitate to open it again! Thanks :)
