### ISSUE TITLE
Pull request #108 rolls back fix #57

### ISSUE THREAD

**Issue by schellingerhout** [npm/how-to-npm#110]
Merge pull request #108 rolls back fix #57 and again causes issue #56 (as well as its related\duplicates #11, #17, #19)  

Tested on windows 10 with npm at location with space "C:\Program Files\nodejs\npm" release 2.4.0 works, 2.4.1 produces the error.

**Comment by schellingerhout** [comment]
Temporary workaround for Windows users that installed npm to a location with a space in the name is to install 2.4.0

    npm install how-to-npm@2.4.0 -g

**Comment by watilde** [comment]
Oh I'm sorry to hear it.. I will have a look it. Thanks for reporting it.

**Comment by watilde** [comment]
Hmm maybe it's better to replace them with `"npm"`. I will test it on my Windows laptop later, and make a patch.

If anyone can take this issue, feel free to do that :)

**Comment by schellingerhout** [comment]
@watilde I believe since the issues you were attempting to fix were actually already addressed, the fix is to roll back to 2.4.0. Mentioning @EmmaRamirez  since she reviewed

**Comment by watilde** [comment]
I'm going to close this as resolved by https://github.com/workshopper/how-to-npm/pull/112
