### ISSUE TITLE
how-to-npm

### ISSUE THREAD

**Issue by akinhwan** [npm/how-to-npm#119]
I am getting "'how-to-npm' is not recognized as an internal or external command, operable program or batch file."

i have how-to-npm@2.4.2 installed already.

**Comment by mokutsu** [comment]
hi @akinhwan are you on windows?  If so, could you try one of the solutions in the following threads? 

http://stackoverflow.com/questions/33055515/npm-is-not-recognized-as-an-internal-or-external-command-operable-program-or
http://stackoverflow.com/questions/20992723/npm-is-not-recognized-as-internal-or-external-command-operable-program-or-bat

**Comment by watilde** [comment]
Hello! Try this command please :)
> npm install -g how-to-npm
