### ISSUE TITLE
Very basic NPM newbie question

### ISSUE THREAD

**Issue by bythckr** [npm/how-to-npm#120]
As a npm newbie, I have a question as to where do I run `npm i -g how-to-npm`.

I am using a mac. Do I run it in `~` as it is `-g`(global)? Or can I run it in a sub folder like `/Documents/Code/js/`?

**Comment by Shivamnema** [comment]
If you have installed your NPM properly with proper permissions. Then you can run this command from any where and it will install "how-to-npm" globally.

**Comment by watilde** [comment]
You can check where npm install modules globally via npm config. Also what @Shivamnema said!
https://docs.npmjs.com/misc/config#global

Closing as resolved. Thanks!
