### ISSUE TITLE
Cannot publish

### ISSUE THREAD

**Issue by emrealtann** [npm/how-to-npm#122]
Hi,
I couldn't publish my package with 'npm publish' command. It throws 404 error:

`c:\sandbox\how-to-npm>npm publish
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 missing : @emrealtann/emrealtann
npm ERR! 404
npm ERR! 404  '@emrealtann/emrealtann' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

I've attached the log file too. Thanks for help.
[2017-04-20T14_36_31_291Z-debug.txt](https://github.com/workshopper/how-to-npm/files/943685/2017-04-20T14_36_31_291Z-debug.txt)

**Comment by marcinwasilewski** [comment]
Unfortunately I get the same issue with the exact same log file. 
When I go to http://localhost:15443 in my browser I get a JSON style response with a single property `error:"missing"`.

**Comment by scaredcat** [comment]
[https://github.com/nodeschool/discussions/issues/1561](https://github.com/nodeschool/discussions/issues/1561) seems to have fixed it
