### ISSUE TITLE
io.js compatibility

### ISSUE THREAD

**Issue by javierjmx** [npm/how-to-npm#13]
It doesn't work with io.js. It displays the following error:

node: ../deps/uv/src/unix/stream.c:1174: uv_shutdown: Assertion `(stream->type == UV_TCP || stream->type == UV_NAMED_PIPE) && "uv_shutdown (unix) only supports uv_handle_t right now"' failed.
Aborted (core dumped)

**Comment by ralphtheninja** [comment]
@elMauNunez It works fine for `v1.6.1` on my machine. Which version of `iojs` are you running? Please close if this is no longer an issue.

**Comment by javierjmx** [comment]
@ralphtheninja I updated io.js and it works fine. I guess it was issue of io.js 1.4.X.
