### ISSUE TITLE
Challenge 00: doesn't tell you how to check version

### ISSUE THREAD

**Issue by nielsbom** [npm/how-to-npm#134]
The 00th challenge tells you what to do but not how to.

- "The first thing we're going to do is make sure that your npm version is up to date."
- "Run `how-to-npm verify` once that is done."

But actually, the way to do this challenge is to give that command, right? That's what worked for me. I can create a PR if this is actually what's wrong. Not sure how to do the i18n though..

**Comment by watilde** [comment]
Hello! I think the challenge is to simply check the user's environment instead of how to `npm -v`.
