### ISSUE TITLE
npm publish has resulted in error "You need to authorize this machine using `npm adduser`"

### ISSUE THREAD

**Issue by furixturi** [npm/how-to-npm#25]
Hi, 

In the **08 Publish** chapter I was not able to `npm publish` against the .npmrc local environment. However it worked when the .npmrc file removed and with a connection to https://www.npmjs.com/. None of the following chapters worked correctly either against this local environment, and all worked well again without the .npmrc file and with a connection to https://www.npmjs.com/.

I once went through the **02 Login** chapter smoothly and `npm whoami` returned the correct info. At this point running `npm whoami` also results in authentication errors.

Looking at the path that `userconfig` in .npmrc pointed to (`userconfig = /Users/xiaoli.shen/.config/how-to-npm/npmrc`), there is no such file or folder named `npmrc`, which might be the reason for the authentication errors.

I'm using version 2.0.0 of how-to-npm and on Mac OS 10.9.5 

My npm-debug.log is as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'adduser' ]
2 info using npm@2.11.1
3 info using node@v0.12.4
4 verbose adduser before first PUT { _id: 'org.couchdb.user:alabebop',
4 verbose adduser   name: 'alabebop',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'alabebop@gmail.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-06-11T09:07:53.405Z' }
5 verbose request uri http://localhost:15443/-/user/org.couchdb.user:alabebop
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 11:07:53
8 verbose request id 8f19ff7f3662cb4c
9 http request PUT http://localhost:15443/-/user/org.couchdb.user:alabebop
10 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
11 info attempt registry request try #2 at 11:08:03
12 http request PUT http://localhost:15443/-/user/org.couchdb.user:alabebop
13 info retry will retry, error on last attempt: Error: connect ECONNREFUSED
14 info attempt registry request try #3 at 11:09:03
15 http request PUT http://localhost:15443/-/user/org.couchdb.user:alabebop
16 verbose request invalidating /Users/xiaoli.shen/.npm/localhost_15443/-/user/org.couchdb.user_3Aalabebop on PUT
17 verbose adduser back [ { [Error: connect ECONNREFUSED]
17 verbose adduser     code: 'ECONNREFUSED',
17 verbose adduser     errno: 'ECONNREFUSED',
17 verbose adduser     syscall: 'connect' },
17 verbose adduser   undefined,
17 verbose adduser   undefined ]
18 verbose stack Error: connect ECONNREFUSED
18 verbose stack     at exports._errnoException (util.js:746:11)
18 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
19 verbose cwd /Users/xiaoli.shen/projects/nodeschool/how-to-npm
20 error Darwin 13.4.0
21 error argv "node" "/usr/local/bin/npm" "adduser"
22 error node v0.12.4
23 error npm  v2.11.1
24 error code ECONNREFUSED
25 error errno ECONNREFUSED
26 error syscall connect
27 error Error: connect ECONNREFUSED
27 error     at exports._errnoException (util.js:746:11)
27 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
27 error  { [Error: connect ECONNREFUSED]
27 error   code: 'ECONNREFUSED',
27 error   errno: 'ECONNREFUSED',
27 error   syscall: 'connect' }
28 error If you are behind a proxy, please make sure that the
28 error 'proxy' config is set properly.  See: 'npm help config'
29 verbose exit [ 1, true ]
```

**Comment by swestcott** [comment]
Ditto, same software versions and same error.

**Comment by meppsilon** [comment]
I'm running into this error as well. Any suggestions on how to bypass it?

**Comment by smirciat** [comment]
Same issue here.  It sounds like @alabebop has a workaround, but I am too new to this environment to understand it.  Is any further guidance available?

**Comment by AnandWalvekar** [comment]
It go resolved!!!
1) Switch to Login module (by typing "how-to-npm" on command line)
2) Type "npm adduser" to login
3) Type "npm whoami" to confirm if logged in
4) Switch back to the package at which you are getting error(my case it was Publish Again)
5) Type "npm publish"
6) Done

**Comment by devhammer** [comment]
@AnandWalvekar That workaround didn't work for me. Still fails to publish, even when npm whomi correctly returns my username.

Getting the following output:

```
npm ERR! publish Failed PUT 404
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v0.12.5
npm ERR! npm  v2.13.3
npm ERR! code E404

npm ERR! 404 missing : @myUser/how-to-npm
npm ERR! 404
npm ERR! 404 '@myUser/how-to-npm' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USERNAME\Documents\node_code\nodeschool.io\how-to-npm\npm-debug.log
```

**Comment by jmanuel1** [comment]
Getting same error as @devhammer, with node v0.10.35 on Windows 10.

**Comment by quangnd** [comment]
AnandWalvekar's solution worked with me!

**Comment by davis3792** [comment]
The work around fixed it for me as well.  Wasted a bunch of time getting there though.

**Comment by su6a12** [comment]
Solution worked for me as well, thanks @AnandWalvekar

**Comment by seonixx** [comment]
Workaround worked for me. Cheers @AnandWalvekar

**Comment by bennythejudge** [comment]
@AnandWalvekar thanks a lot it worked but I had to bump the version.
Could a skip be provided for this step?

**Comment by jondcoleman** [comment]
Also had this error and workaround worked for me.

**Comment by aclbros** [comment]
Workaround worked for me. Cheers @AnandWalvekar

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/how-to-npm/issues/46. i believe the windows problem is already doc'd in #37

**Comment by agungsantoso** [comment]
AnandWalvekar's solution worked with me!

**Comment by sawant** [comment]
I have documented the issue and solution here https://github.com/npm/how-to-npm/issues/8#issuecomment-201192289 .

**Comment by piyushdubey** [comment]
@AnandWalvekar's solution worked for me as well!

**Comment by lpix** [comment]
@AnandWalvekar's solution worked for me! I suggest adding this as a tip in the module in case someone  has the same issue

**Comment by sudoVlad** [comment]
@AnandWalvekar Thanks for the solution

**Comment by swheatley** [comment]
I had to go through the steps a few times but the work around for the solution mentioned above does work :)

**Comment by sergiomgaspar** [comment]
@AnandWalvekar thx for the WA.. worked like a charm :)

**Comment by ravikishorethella** [comment]
I am not able to pass the Publish Again challenge. I have tried @AnandWalvekar's solution but still no luck.

![error](https://user-images.githubusercontent.com/15951682/28100458-323ebf4a-6690-11e7-8d87-3759030ea962.PNG)

**Comment by alundiak** [comment]
@AnandWalvekar solution works for me locally. but At the moment I can't figure out why the same flow doesn't work on Jenkins.
If someone has ideas, I will very thankful.

This is cut from my custom .npmrc file created by Jenkins.
```
; userconfig /home/builder/.jenkins/jobs/FDD test - simple project/workspace@tmp/config3550090785588839693tmp
always-auth = true
registry = "https://my-server.com:8443/repository/my-hosted-npm"
strict-ssl = false
```


`always-auth = true` means, that I provided NPM user credentials on jenkins level, and I expected Jenkins pass/substitute creds during `npm publish` but I can't get why it doens't work..

**Comment by renatoathaydes** [comment]
Does not work!

```
npm adduser
Username: xxxxxx
Password:
Email: (this IS public) xxxxxx@hotmail.com
Logged in as xxxxx on https://registry.npmjs.org/.
➜  lib1 npm publish
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by alundiak** [comment]
@renatoathaydes  
1) What OS u have?
2) what is ur `.npmrc` content or 
3) what is output of `npm config list`?

I see, you have `https://registry.npmjs.org/` as registry, so I assume `npm get registry` will show it. have you tried to change to `http://registry.npmjs.org/` (http).

4) `strict-ssl = false` set?
5) Are u under/behind the some proxy/vpn?

**Comment by renatoathaydes** [comment]
OS: Linux renato 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
//registry.npmjs.org/:_authToken=cef314xxxxxxx
init.author.name=Renato Athaydes
init.author.email=renatoathaydes@xxxx
```

```
➜  npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v9.4.0 linux x64"

; userconfig /home/renato/.npmrc
init.author.email = "renatoathaydes@xxxx"
init.author.name = "Renato Athaydes"

; node bin location = /home/renato/.nvm/versions/node/v9.4.0/bin/node
; cwd = /home/renato/programming/projects/node-lib-mismatch/lib3
; HOME = /home/renato
; "npm config ls -l" to show all defaults.
```

I am at home, no proxies. No `strict-ssl = false` that I can see. And I would prefer to not use `http`.

**Comment by yordis** [comment]
I keep getting the same error even when I successfully login. `npm whoam` give me the correct user but it keep failing no matter what.

**Comment by JMuhire** [comment]
In my ci script, I have resolved this issue using a _auth token and setting up the user email like this : 

`npm config set _auth $NPM_REGISTRY_TOKEN && npm config set registry $NPM_REGISTRY_URL && npm config set always-auth=true && npm config set email=email@email.com`

**Comment by petermetz** [comment]
My issue was that I had the `publishConfig` object specified in `package.json` which defined an invalid URL (some private registry). 
Had to set it up like this:
```json
  "publishConfig": {
    "registry": "https://registry.npmjs.org/"
  },
```

**Comment by zrubing** [comment]
I use `npm whoami` and is correct.

**Comment by zrubing** [comment]
`npm whoami` is correct
I use `sudo npm publish` is failure,when i switch back to normal user then it worked

**Comment by Bittttter** [comment]
I just delete currentdir/.npmrc and then use `nrm use` to switch npm registry. And It works.

**Comment by geoidesic** [comment]
@Bittttter  `nrm use` is not a thing.  ?

**Comment by Carnia** [comment]
> My issue was that I had the `publishConfig` object specified in `package.json` which defined an invalid URL (some private registry).
> Had to set it up like this:
> 
> ```json
>   "publishConfig": {
>     "registry": "https://registry.npmjs.org/"
>   },
> ```

yes, when i delete `publishConfig ` in package.json，I can publish it normally。

**Comment by TylerSustare** [comment]
I had to go pro, publish the package, make the package public, and open a ticket to get my money back. It was super stupid.

**Comment by zuenir** [comment]
> It go resolved!!!
> 
> 1. Switch to Login module (by typing "how-to-npm" on command line)
> 2. Type "npm adduser" to login
> 3. Type "npm whoami" to confirm if logged in
> 4. Switch back to the package at which you are getting error(my case it was Publish Again)
> 5. Type "npm publish"
> 6. Done

Thank you, it helped to solve my problem

**Comment by sinawic** [comment]
> In my ci script, I have resolved this issue using a _auth token and setting up the user email like this :
> 
> `npm config set _auth $NPM_REGISTRY_TOKEN && npm config set registry $NPM_REGISTRY_URL && npm config set always-auth=true && npm config set email=email@email.com`

@JMuhire 
its 2024 and I wanna thank u for this!

i just added
`registry=`
`_authToken=`
to the `.npmrc` file and it workeddd
