### ISSUE TITLE
how-to-npm on windows

### ISSUE THREAD

**Issue by Quas94** [npm/how-to-npm#31]
Can't get past the very first step (verifying npm is up-to-date).

```
C:\Users\Quasar\Desktop\how-to-npm>how-to-npm verify
verifying that npm is installed...
Uh oh!  npm had a problem! {"killed":false,"code":1,"signal":null,"cmd":"C:\\Win
dows\\system32\\cmd.exe /s /c \"C:\\Program Files\\nodejs\\npm.CMD --version\""}

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

Looks like something to do with the space in the Program Files folder.
Anything I can do about this other than re-installing Node itself to a different folder that doesn't have space characters?

**Comment by Quas94** [comment]
I just completed all the steps whilst skipping verification for the parts which produced this error. Just a heads up that this issue exists, though.

**Comment by No9** [comment]
There are 3 patches that attempt to to solve this 

https://github.com/npm/how-to-npm/pull/17
https://github.com/npm/how-to-npm/pull/19
https://github.com/npm/how-to-npm/pull/32 

And this was the original bug report 
https://github.com/npm/how-to-npm/issues/11 

@isaacs @mmalecki @linclark 
Please can we get this in somehow?

**Comment by kaiyoma** [comment]
Seeing this as well. Quotes around the file location of the npm executable are necessary on Windows because the default install location for Node.js has spaces in its name.

**Comment by kaiyoma** [comment]
The problem seems to be worse now than when the OP submitted the issue. I can't advance past step 2 (Login) because attempting to skip verification also results in an error:

```
...\Kyle\Portfolio\Studying\temp-workspace> how-to-npm verify
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Uh oh!
It looks like something went wrong
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################



...\Kyle\Portfolio\Studying\temp-workspace> how-to-npm verify skip
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Uh oh!
It looks like something went wrong
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

**Comment by 8fdafs2** [comment]
try run how-to-npm in 'Node.js command prompt' see if it solves the problem

**Comment by cltsao** [comment]
@8fdafs2 Thanks. Running how-to-npm in Node.js command prompt solved the problem in my Windows environment.

**Comment by itzsaga** [comment]
Just updating with my error. This is still an issue and needs more instruction for people to work around.

```js
λ how-to-npm verify
verifying that npm is installed...
Uh oh!  npm had a problem! {"killed":false,"code":1,"signal":null,"cmd":"C:\\Program Files\\nodejs\\npm.CMD --version"}
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

**Comment by itzsaga** [comment]
Possible solution:
Instruct people on Windows to run `npm -v` and if the version is high enough instruct people to run `how-to-npm verify skip`. Otherwise upgrade npm via `npm install npm`.
I believe this could solve this issue but I'm not 100% on this idea.

**Comment by watilde** [comment]
#108 is shipeed as v2.4.1. Closing as resolved :)
