### ISSUE TITLE
how-to-npm verify on the Login module doesn't run

### ISSUE THREAD

**Issue by kotAPI** [npm/how-to-npm#37]
I checked my working directory, I am in the how-to-npm folder and when I run the command to verify, This is what I get.

Kothapalli@KOTHAPALLI-PC ~/how-to-npm (master)
$ npm whoami
kotapi

Kothapalli@KOTHAPALLI-PC ~/how-to-npm (master) 
$ how-to-npm verify
'c:\Program' is not recognized as an internal or external command,
operable program or batch file.

Uh oh!
It looks like something went wrong
###### 
######

**Comment by ashleygwilliams** [comment]
related #17 #19 #32 #33

**Comment by watilde** [comment]
https://github.com/workshopper/how-to-npm/pull/108 is shipeed as `v2.4.1`. Closing as resolved :)
