### ISSUE TITLE
04 Install A Module Could not install linclark/pkg

### ISSUE THREAD

**Issue by highmax** [npm/how-to-npm#38]
Error:

npm install @linclark/pkg
npm WARN package.json folder@1.0.0 No repository field.
npm WARN package.json folder@1.0.0 No README data
npm ERR! git clone git@github.com:linclark/pkg Cloning into bare repository '/Users/XumaK/.npm/_git-remotes/git-github-com-linclark-pkg-37223368'...
npm ERR! git clone git@github.com:linclark/pkg ERROR: Repository not found.
npm ERR! git clone git@github.com:linclark/pkg fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:linclark/pkg 
npm ERR! git clone git@github.com:linclark/pkg Please make sure you have the correct access rights
npm ERR! git clone git@github.com:linclark/pkg and the repository exists.
npm ERR! addLocal Could not install linclark/pkg
npm ERR! Error: ENOENT, stat 'linclark/pkg'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/XumaK/.nvm/v0.10.38/bin/node" "/Users/XumaK/.nvm/v0.10.38/bin/npm" "install" "@linclark/pkg"
npm ERR! cwd /Users/XumaK/Documents/Pruebas/nodeschool/how-to-npm/folder
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path linclark/pkg
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/XumaK/Documents/Pruebas/nodeschool/how-to-npm/folder/npm-debug.log
npm ERR! not ok code 0

Log:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/XumaK/.nvm/v0.10.38/bin/node',
1 verbose cli   '/Users/XumaK/.nvm/v0.10.38/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@linclark/pkg' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 warn package.json folder@1.0.0 No repository field.
5 warn package.json folder@1.0.0 No README data
6 verbose readDependencies using package.json deps
7 verbose cache add [ '@linclark/pkg', null ]
8 verbose cache add name=undefined spec="@linclark/pkg" args=["@linclark/pkg",null]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: '@linclark/pkg',
9 verbose parsed url   path: '@linclark/pkg',
9 verbose parsed url   href: '@linclark/pkg' }
10 verbose cache add name="" spec="linclark/pkg" args=["","linclark/pkg"]
11 verbose parsed url { protocol: null,
11 verbose parsed url   slashes: null,
11 verbose parsed url   auth: null,
11 verbose parsed url   host: null,
11 verbose parsed url   port: null,
11 verbose parsed url   hostname: null,
11 verbose parsed url   hash: null,
11 verbose parsed url   search: null,
11 verbose parsed url   query: null,
11 verbose parsed url   pathname: 'linclark/pkg',
11 verbose parsed url   path: 'linclark/pkg',
11 verbose parsed url   href: 'linclark/pkg' }
12 silly lockFile d3fddcad-linclark-pkg linclark/pkg
13 verbose lock linclark/pkg /Users/XumaK/.npm/d3fddcad-linclark-pkg.lock
14 info maybeGithub Attempting linclark/pkg from git://github.com/linclark/pkg
15 silly lockFile 197f35eb-git-github-com-linclark-pkg git://github.com/linclark/pkg
16 verbose lock git://github.com/linclark/pkg /Users/XumaK/.npm/197f35eb-git-github-com-linclark-pkg.lock
17 verbose addRemoteGit [ 'git://github.com/linclark/pkg', 'master' ]
18 verbose git clone git://github.com/linclark/pkg Cloning into bare repository '/Users/XumaK/.npm/_git-remotes/git-github-com-linclark-pkg-197f35eb'...
18 verbose git clone git://github.com/linclark/pkg fatal: remote error:
18 verbose git clone git://github.com/linclark/pkg   Repository not found.
19 silly lockFile 197f35eb-git-github-com-linclark-pkg git://github.com/linclark/pkg
20 silly lockFile 197f35eb-git-github-com-linclark-pkg git://github.com/linclark/pkg
21 info maybeGithub Attempting linclark/pkg from git+ssh://git@github.com:linclark/pkg
22 silly lockFile 37223368-git-github-com-linclark-pkg git@github.com:linclark/pkg
23 verbose lock git@github.com:linclark/pkg /Users/XumaK/.npm/37223368-git-github-com-linclark-pkg.lock
24 verbose addRemoteGit [ 'git@github.com:linclark/pkg', 'master' ]
25 error git clone git@github.com:linclark/pkg Cloning into bare repository '/Users/XumaK/.npm/_git-remotes/git-github-com-linclark-pkg-37223368'...
25 error git clone git@github.com:linclark/pkg ERROR: Repository not found.
25 error git clone git@github.com:linclark/pkg fatal: Could not read from remote repository.
25 error git clone git@github.com:linclark/pkg
25 error git clone git@github.com:linclark/pkg Please make sure you have the correct access rights
25 error git clone git@github.com:linclark/pkg and the repository exists.
26 silly lockFile 37223368-git-github-com-linclark-pkg git@github.com:linclark/pkg
27 silly lockFile 37223368-git-github-com-linclark-pkg git@github.com:linclark/pkg
28 silly lockFile d3fddcad-linclark-pkg linclark/pkg
29 silly lockFile d3fddcad-linclark-pkg linclark/pkg
30 error addLocal Could not install linclark/pkg
31 error Error: ENOENT, stat 'linclark/pkg'
32 error If you need help, you may report this _entire_ log,
32 error including the npm and node versions, at:
32 error     http://github.com/npm/npm/issues
33 error System Darwin 14.1.0
34 error command "/Users/XumaK/.nvm/v0.10.38/bin/node" "/Users/XumaK/.nvm/v0.10.38/bin/npm" "install" "@linclark/pkg"
35 error cwd /Users/XumaK/Documents/Pruebas/nodeschool/how-to-npm/folder
36 error node -v v0.10.38
37 error npm -v 1.4.28
38 error path linclark/pkg
39 error code ENOENT
40 error errno 34
41 verbose exit [ 34, true ]

**Comment by soldair** [comment]
you will need to upgrade npm. please run 

```
sudo npm install -g npm
```

before some version of 2 the npm cli did not have support for scoped modules and parsed them as git dependencies.

**Comment by ashleygwilliams** [comment]
hi @highmax ! did you see @soldair's suggestion? closing issue, plz reopen if you are still having this problem.
