### ISSUE TITLE
04: OK vs NOT OK distinction is confusing

### ISSUE THREAD

**Issue by linclark** [npm/how-to-npm#4]
This distinction could be confusing to new users. Since they probably don't know what OK is supposed to look like, it's asking them to make a choice which they don't have the information to make. It should instead be clear about the output that they should use to determine whether it's ok or not ok.

**Comment by ralphtheninja** [comment]
:+1:

**Comment by sachinag-zz** [comment]
+1 on this being confusing - going through these exercises at Node School SF, where thankfully there are awesome mentors.
