### ISSUE TITLE
Workshop not working properly

### ISSUE THREAD

**Issue by EdiFirst** [npm/how-to-npm#41]
Its not working as should work, I runned the first one ok, then its entry on loop and not go to the next exercise. :(

**Comment by ashleygwilliams** [comment]
hi @EdiFirst ! this is not nearly enough information or context for me to be able to help you. can you please file another issue with more information. also please look through other issues first to see if anyone else has experienced and reported your problem.

**Comment by EdiFirst** [comment]
So, my environment was approved : 
verifying that npm is installed...
You have version 3.3.8 installed.  Great!
Now let's see what the latest version is... wait for it...
The latest npm is: 3.3.8
Congratulations!
You have a recent version of npm installed!

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@     YOUR SOLUTION IS CORRECT!     @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

 But when I go to menu again its still are in question 1, and stay in this "loop":

![sample](https://cloud.githubusercontent.com/assets/3306865/10653058/a3acae1c-783a-11e5-87eb-77bf47dfd1d8.png)
