### ISSUE TITLE
06-npm-test clarity?

### ISSUE THREAD

**Issue by TheHexorcist** [npm/how-to-npm#43]
It could just be me but I have no clue what I'm doing here?  What exactly goes in the "node test.js" file?  I almost get the impression that the user is suppose to understand everything about node.js at this step.  imagine seeing this for the first time

"scripts": {
    "test": "node test.js"
  }

All I know is that this is a json object.

**Comment by TheHexorcist** [comment]
I also noticed that in the object it says "node test.js" and the file name is described as "test.js"

**Comment by TheHexorcist** [comment]
There probably needs to be some remedial understanding of node.js before starting how-to-npm

**Comment by ashleygwilliams** [comment]
related #24

**Comment by compsci78** [comment]
Is anyone going to update this repo? There are numerous pull requests.
