### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by martinheidegger** [npm/how-to-npm#44]
There are plenty of open PR's. Most of which seem to be good. @linclark  @isaacs Do you intend to maintain it? Is there a way to get updates in this nice (and very important) adventure?

**Comment by ashleygwilliams** [comment]
hi @martinheidegger! @linclark no longer works with us, but i do hope to try to clean up and then continue to maintain this project. i only started recently, so it may take a second to get up and running. thanks so much for your PRs and your attention to this.

p.s. i am a huge martin heidegger (german philosopher) -- are you also or do you happen to just have the same name?

**Comment by martinheidegger** [comment]
Hi @ashleygwilliams Oh! Glad that you can take over the work. 

p.s. I just "happen" to have the same name. But as with most coincidents there comes a set of relations: i.e. my parents like heidegger so they thought martin might be a good first name. Because I am called like this I had to read the books. I also often get into conversation with philosophy friends which makes it all more clear what impact he had. I am not sure I can say without bias if I am a fan or not :)

**Comment by ashleygwilliams** [comment]
<3 i use him in conf talks all the time 
![11122067_10100138275162303_109194778709462722_o](https://cloud.githubusercontent.com/assets/1163554/10640802/4e4b678e-77e4-11e5-9f0a-f51151a6f507.jpg)

**Comment by martinheidegger** [comment]
Awesome :+1:
