### ISSUE TITLE
Progress did not update

### ISSUE THREAD

**Issue by EdiFirst** [npm/how-to-npm#47]
Hi @ashleygwilliams ! 
  I don't know why you closed my issue #41 , its still not solved:

So, my environment was approved : 
verifying that npm is installed...
You have version 3.3.8 installed. Great!
Now let's see what the latest version is... wait for it...
The latest npm is: 3.3.8
Congratulations!
You have a recent version of npm installed!

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@ YOUR SOLUTION IS CORRECT! @@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

But when I go to menu again its still are in question 1, and stay in this "loop":
![status of the menu](https://cloud.githubusercontent.com/assets/3306865/10653058/a3acae1c-783a-11e5-87eb-77bf47dfd1d8.png)

**Comment by pippinlee** [comment]
FWIW, you should be able to change lessons (via up/down arrow keys and enter key). If you can't change lessons that way, that'd be a great issue to bring up.

**Comment by bengl** [comment]
As @pippinlee mentioned, you can use the arrows keys to move around the menu.

Having the first lesson selected when the workshop starts up is normal for workshops using https://github.com/substack/adventure, which `how-to-npm` uses, so if that behavior seems incorrect to you, you should open an issue there.
