### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by watilde** [npm/how-to-npm#59]
Nowaday, some major workshoppers supported i18n and it's obviously helpful especially for beginners. I would like to get your thoughts on multilingual support.

Technically, current `how-to-npm` is using the `adventure` module and it can't support i18n. Also, [current way](https://github.com/npm/how-to-npm/blob/master/problems/00-install-npm.js#L2-L22) to display question texts is not easy to integrate `workshopper-adventure` which are used by another workshoppers to support i18n.

e.g.
- https://github.com/sethvincent/javascripting
- https://github.com/workshopper/learnyounode

[This PR](https://github.com/npm/how-to-npm/pull/20) was too large to review. Let me subdivide the PR to do again realistically:
1. separate question texts from actual codes 
2. Integrate `workshopper-adventure` instead of the `adventure`
3. Add another language sources

**Comment by martinheidegger** [comment]
Done I think.

**Comment by watilde** [comment]
Yes we did it ;)
