### ISSUE TITLE
package.json not found

### ISSUE THREAD

**Issue by ghost** [npm/how-to-npm#6]
In section 06, `how-to-npm verify` tells you to return to section 01 if your package.json has a syntax error (such as a missing comma). The error messages in section 01 and 06 suggest that there is no package.json file in this case. There should be a more helpful error message

**Comment by watilde** [comment]
Since it is an issue made more than a year ago and there are few reporters. I think that this has already been resolved so that I will close the issue, but please open it again if you're still having the same issue!

Thanks.
