### ISSUE TITLE
11 Dist Tag/  Have problem to add a tag

### ISSUE THREAD

**Issue by NLStom** [npm/how-to-npm#69]
I have problem in this section 
When I enter npm dist-tag add tom5208@1.0.0 old
It gave me following error 

Caimings-MacBook-Pro:nodejs NLStom$ npm dist-tag add tom5208@1.0.0 old
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "dist-tag" "add" "tom5208@1.0.0" "old"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code E404

npm ERR! 404 missing : -/package/tom5208/dist-tags

Also in 08 Publish section 
when I enter npm view tom5208, it doesn't print out anything.

I suspect my package's name is not  tom5208? below are few line of my package.json file
{
  "name": "tom5208",
  "version": "1.0.1",
  "description": "this is begining",
  "main": "index.js",

So I guess my package's name is tom5208

Please help...

**Comment by watilde** [comment]
Hello! You're using the old version of the npm which is not maintained anymore.
> npm ERR! npm v2.15.8

Using the latest stable version is always necessary to avoid this kind of issues. Could you please try to update the version of your npm? This documentation may support you: https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

Thanks!

**Comment by NLStom** [comment]
Thank you so much for the reply!
