### ISSUE TITLE
Move to workshopper org

### ISSUE THREAD

**Issue by martinheidegger** [npm/how-to-npm#73]
Hello @npm

I would like to extend the offer to move how-to-npm to the general organisation for workshoppers of nodeschool to https://github.com/workshopper/org.

best regards
Martin Heidegger

cc. @ashleygwilliams @llkats @jpwesselink

**Comment by ashleygwilliams** [comment]
i've pinged @isaacs internally, and now also here.

**Comment by isaacs** [comment]
+1. Please to be transferring the workshop to the workshop org. Thanks!!

**Comment by martinheidegger** [comment]
@ashleygwilliams Will you transfer it or should I add someone else to the workshopper org to make this happen?

**Comment by isaacs** [comment]
Hi, @martinheidegger I need you to add me to the workshopper org to make this happen.

**Comment by martinheidegger** [comment]
Invitation sent.

**Comment by martinheidegger** [comment]
Done! Cool!
