### ISSUE TITLE
failed npm install -g how-to-mpn

### ISSUE THREAD

**Issue by pjwok** [npm/how-to-npm#76]
here is my problem, what is wrong? Pls help me, thanks!

`C:\Windows\System32>npm -v
2.15.9

C:\Windows\System32>node -v
v4.5.0

C:\Windows\System32>npm install -g how-to-npm
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\ruanjian\nj\node.exe" "D:\ruanjian\nj\node_modules\npm\bin\npm-cli.js" "install" "-g" "how-to-npm"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! shasum check failed for C:\Users\ADMINI~1\AppData\Local\Temp\npm-7900-ecd30d56\registry.npmjs.org\how-to-npm-\how-to-npm-2.0.0.tgz
npm ERR! Expected: 590f1a8d0b63ed7c9fe7cceaf58c6fb7bdcc8980
npm ERR! Actual:   62ffe898b5e66570e0842dba367b63c107032527
npm ERR! From:     https://registry.npmjs.org/how-to-npm/-/how-to-npm-2.0.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
`

**Comment by watilde** [comment]
Hello! You're using very old version of npm.

    `C:\Windows\System32>npm -v
    2.15.9

Could you please try to update it? This doc may support you to do that:
https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

Thanks.
