### ISSUE TITLE
How to UPDATE the package?

### ISSUE THREAD

**Issue by sonichanxiao** [npm/how-to-npm#81]
I am up to step 14 Update, but I couldn't get through.

If I run npm-outdated, I have
Package        Current  Wanted  Latest  Location
@linclark/pkg    1.0.2   1.0.2   1.0.1  @myusername/npm-dev

I only can update the Current version 1.0.2 to 1.0.1, but how could the latest version 1.0.1 is lower than the wanted or current version? How I can update it?

Thank you.

**Comment by watilde** [comment]
Hmm, it's wired indeed that updating the version to `1.0.1` from `1.0.2` doesn't mean updating.
Could you please try remove your `node_modules` and install again? Then `npm outdated` hopefully display nothing.

**Comment by watilde** [comment]
Since ten days passed, I will close this. If you haven't already resolved, please do not hesitate to open it again!
