### ISSUE TITLE
FYI: Owner update

### ISSUE THREAD

**Issue by martinheidegger** [npm/how-to-npm#82]
On request from @watilde 

> Could you put me into this list to ship the next version?

https://twitter.com/watilde/status/817308498270765057

I added him to the npm owner list since he is the maintainer of `how-to-npm`. 
I also removed myself as owner since I am busy with other things.

cc. @workshopper/deploy

**Comment by watilde** [comment]
I've confirmed that I'm on the list. Thanks!
+ https://www.npmjs.com/package/how-to-npm/access

Then I will ship the latest version as a minor-update later.

**Comment by watilde** [comment]
Ok, I've pubslished the latest version as `v2.1.0`. Thanks!
```
$ npm view how-to-npm versions
[ '0.0.0', '1.0.0', '1.1.1', '1.2.0', '2.0.0', '2.1.0' ]
```
