### ISSUE TITLE
uninstalled and installed again, gives an error 

### ISSUE THREAD

**Issue by Hassanbhb** [npm/how-to-npm#88]
hello, 

so when i was about to do the login challenge, the git command didn't work, i didn't install git in the first place, so stupid me thought that something messed up when installing , and run npm uninstall -g how-to-npm

but when i tried to install again a bunch of errors appeared like this

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dell\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "how-to-npm"
npm ERR! node v7.3.0
npm ERR! npm  v4.1.1
npm ERR! path C:\Users\Dell\AppData\Roaming\npm\node_modules\how-to-npm
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\Dell\AppData\Roaming\np
m\node_modules\how-to-npm'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Dell\Desktop\testnode\npm-debug.log
```

how do i fix this?

**Comment by watilde** [comment]
Could you try the same command with `Run as Administrator`?

Related issue report
+ https://github.com/npm/npm/issues/13461

**Comment by watilde** [comment]
Since over ten days passed already, I will close this. If you haven't resolved it yet, please do not hesitate to open it again! Thanks :)
