### ISSUE TITLE
verify dist-tag (point 11) remove tags

### ISSUE THREAD

**Issue by ginopc** [npm/how-to-npm#99]
After added some tag (dist-tag add) and launched "how-to-npm verify" tag removed by verify.
Follows reporting:

~/workspace (master) $ npm dist-tag ls 
alpha: 1.0.1
latest: 1.0.3
~/workspace (master) $ how-to-npm verify
Uh oh, looks like you still only have a single dist-tag.
Use `npm help dist-tag` to learn how to add another one.
~/workspace (master) $ npm dist-tag ls 
latest: 1.0.3

**Comment by watilde** [comment]
Hello!

Could you give me the command history if it's possible? I couldn't reproduce it, and couldn't find a process that removes the old tag in the code: https://github.com/workshopper/how-to-npm/blob/master/problems/11-dist-tag/index.js

**Comment by ginopc** [comment]
you can remove dist-tag with command 
`npm dist-tag rm <pkg> <tag>`

**Comment by ginopc** [comment]
Follows command history:
`
npm version 1.0.1
npm dist-tag add @user/pkg@1.0.1 alpha
npm version 1.0.2
npm dist-tag add @user/pkg@1.0.2 beta
npm version 1.0.3
`

Running how-to-npm verify it remove tag alpha

**Comment by ginopc** [comment]
Follows command history:

npm version 1.0.1
npm dist-tag add @user/pkg@1.0.1 alpha
npm version 1.0.2
npm dist-tag add @user/pkg@1.0.2 beta
npm version 1.0.3

Running how-to-npm verify it remove tag alpha
